### ISSUE TITLE
使用"无损（VIP）"和"Hi-Res（VIP）"播放部分歌曲时报错

### ISSUE THREAD

**Issue by mcwuguodadi** [FengLiuFeseliud/CloudMusic-Mod#12]
# 问题描述
使用"无损（VIP）"和"Hi-Res（VIP）"播放部分歌曲时报错

测试使用歌曲：[この歌声届きますか？](https://music.163.com/song?id=1363319939&)与[恋爱漫画♡](https://music.163.com/song?id=1877685462&)
# 报错信息
```
[14:53:27] [CloudMusicPlayer thread/INFO]: [STDOUT]: FLAC
[14:53:27] [CloudMusicPlayer thread/INFO]: [STDERR]: java.lang.IllegalArgumentException: Unsupported conversion: PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian from FLAC 44100.0 Hz, 24 bit, stereo, unknown frame size, unknown frame rate
[14:53:27] [CloudMusicPlayer thread/INFO]: [STDERR]: 	at java.desktop/javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:892)
[14:53:27] [CloudMusicPlayer thread/INFO]: [STDERR]: 	at fengliu.cloudmusic.util.MusicPlayer.play(MusicPlayer.java:139)
[14:53:27] [CloudMusicPlayer thread/INFO]: [STDERR]: 	at fengliu.cloudmusic.util.MusicPlayer.play(MusicPlayer.java:191)
[14:53:27] [CloudMusicPlayer thread/INFO]: [STDERR]: 	at fengliu.cloudmusic.util.MusicPlayer.playMusic(MusicPlayer.java:123)
[14:53:27] [CloudMusicPlayer thread/INFO]: [STDERR]: 	at fengliu.cloudmusic.util.MusicPlayer.run(MusicPlayer.java:62)
[14:53:27] [CloudMusicPlayer thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
[14:53:27] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <texture> is not a valid texture name.'
```
# 一些可能有用的信息
Minecraft版本：1.20.1
模组版本：0.4.5
Fabric加载器版本：0.14.21
Fabric API：0.85.0

**Comment by mcwuguodadi** [comment]
日志861行处
[latest.log](https://github.com/FengLiuFeseliud/CloudMusic-Mod/files/12066800/latest.log)

补充说明：mod会跳过出现这类问题的歌曲，直接播放下一首能正常播放的歌曲

**Comment by mcwuguodadi** [comment]
准备了一份只有cloudmusic-mod-1.20.x-0.4.5及其前置的日志以排除与其他mod的兼容性问题
[latest.log](https://github.com/FengLiuFeseliud/CloudMusic-Mod/files/12066873/latest.log)

**Comment by FengLiuFeseliud** [comment]
没会员测不出这 bug, 先其它音质用, 我修修(

**Comment by GLDYM** [comment]
我尝试修改了输出流的采样深度，改为与输入流相同（如果未指定则为16bit），依然报错。
所以问题出在现在的java原生还不支持24bit音频的转换，如果要解决这个问题的话估计要引入其他的java库。
```
[21:19:48] [CloudMusicPlayer thread/INFO]: [STDOUT]: FLAC 44100.0 Hz, 24 bit, stereo, unknown frame size, unknown frame rate
[21:19:48] [CloudMusicPlayer thread/INFO]: [STDERR]: java.lang.IllegalArgumentException: Unsupported conversion: PCM_SIGNED 44100.0 Hz, 24 bit, stereo, 4 bytes/frame, little-endian from FLAC 44100.0 Hz, 24 bit, stereo, unknown frame size, unknown frame rate
[21:19:48] [CloudMusicPlayer thread/INFO]: [STDERR]: 	at java.desktop/javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:892)
[21:19:48] [CloudMusicPlayer thread/INFO]: [STDERR]: 	at fengliu.cloudmusic.util.MusicPlayer.play(MusicPlayer.java:139)
[21:19:48] [CloudMusicPlayer thread/INFO]: [STDERR]: 	at fengliu.cloudmusic.util.MusicPlayer.play(MusicPlayer.java:191)
[21:19:48] [CloudMusicPlayer thread/INFO]: [STDERR]: 	at fengliu.cloudmusic.util.MusicPlayer.playMusic(MusicPlayer.java:123)
[21:19:48] [CloudMusicPlayer thread/INFO]: [STDERR]: 	at fengliu.cloudmusic.util.MusicPlayer.run(MusicPlayer.java:62)
[21:19:48] [CloudMusicPlayer thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```
