### ISSUE TITLE
1.19.3 mod0.4.2 即使已经使用最新版Fabric API，但仍然报错需要api

### ISSUE THREAD

**Issue by muausees** [FengLiuFeseliud/CloudMusic-Mod#6]
报错信息如下：

A potential solution has been determined:
         - Install api, any version.
Unmet dependency listing:
         - Mod 'CloudMusic' (cloudmusic) 0.4.2 requires any version of api, which is missing!
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.13.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) ~[?:?]
        at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]

**Comment by RTAkland** [comment]
看这里, https://github.com/FengLiuFeseliud/CloudMusic-Mod/pull/7

**Comment by FengLiuFeseliud** [comment]
Fabric 这个 mod json 中的 fabric  api 真的各种问题。。。晚点发修复的版本
